## Notebook for generating the dataset for toy example

In this notebook we generate the toy example data for sanity checking our methods. The data is $(x, y) \in \mathbb{R}^3 \times \{0, 1\}$ for any training pair in the dataset. We train on datasets with both explanations $(x_1, x_2)$ and $(x_2, x_3)$ (and any permutation thereof) and test on seperate test sets that only include one of the explanations. 

In [100]:
import os
import torch 
BASE_DIR = '../data/toy_example'

Generating the training examples, currently we only use the simple classification function: $\text{sign}(x_1 + x_2) > 0 \Rightarrow 1$.

In [88]:
def gen_data(func, train_size: int = 10000):
    training_examples = torch.randn((train_size, 3))
    training_examples[:, 2] = training_examples[:, 0]
    training_labels = func(training_examples).unsqueeze(dim=-1).int()

    return training_examples, training_labels

def simple_decs_func(training_examples: torch.Tensor):
    return (training_examples[:, 0] + training_examples[:, 1]) > 0

training_simple = gen_data(simple_decs_func)
training_simple[0][:5], training_simple[1][:5]

(tensor([[-0.4600,  0.0640, -0.4600],
         [-0.5983,  0.8440, -0.5983],
         [-1.2186, -0.1842, -1.2186],
         [-0.4399,  0.9788, -0.4399],
         [ 1.8392, -0.7033,  1.8392]]),
 tensor([[0],
         [1],
         [0],
         [1],
         [1]], dtype=torch.int32))

In [89]:
def gen_test_sets(func, test_size: int = 1000, inter: bool = False):
    expl_1_training = torch.randn((test_size, 3)) # explanation of (x1, x2)
    expl_1_training[:, 2] = expl_1_training[:, 0]
    expl_1_labels = func(expl_1_training).unsqueeze(dim=-1).int()
    if inter:
        expl_1_training[:, 2] = 20
    else:
        expl_1_training[:, 2] = torch.randn_like(expl_1_training[:, 2]) * 2 + 5 # rand out x3 so only x1, x2 can be used
    
    expl_2_training = torch.randn((test_size, 3)) # explanation of (x2, x3)
    expl_2_training[:, 2] = expl_2_training[:, 0]
    expl_2_labels = func(expl_2_training).unsqueeze(dim=-1).int()
    if inter:
        expl_2_training[:, 0] = 20
    else:
        expl_2_training[:, 0] = torch.randn_like(expl_1_training[:, 0]) * 2 + 5 # rand out x1 so only x3, x2 can be used
    
    return (expl_1_training, expl_1_labels), (expl_2_training, expl_2_labels)

test_sets = gen_test_sets(simple_decs_func, inter=True)

In [90]:
test_sets[0][0][:5], test_sets[0][1][:5]

(tensor([[-5.3028e-03,  1.3325e+00,  2.0000e+01],
         [ 1.1445e+00, -1.8813e+00,  2.0000e+01],
         [-8.7725e-02, -1.6157e+00,  2.0000e+01],
         [ 1.4730e-01,  6.6496e-01,  2.0000e+01],
         [-6.3954e-01,  1.7280e+00,  2.0000e+01]]),
 tensor([[1],
         [0],
         [0],
         [1],
         [1]], dtype=torch.int32))

In [91]:
# use .pt as its more optimized for torch tensors
save_path_simple = os.path.join(BASE_DIR, 'simple_func_dataset_int.pt')
torch.save({'training_x': training_simple[0],
            'training_y': training_simple[1],
            'test1_x': test_sets[0][0],
            'test1_y': test_sets[0][1],
            'test2_x': test_sets[1][0],
            'test2_y': test_sets[1][1],
            }, save_path_simple)

We can also try a more complicated function: $\text{sin}(x_1 + x_2) > 0 \Rightarrow 0$.

In [92]:
def sine_decs(training_examples):
    return torch.sin(training_examples[:, 0] + training_examples[:, 2]) > 0

training_sine = gen_data(sine_decs)
test_sets = gen_test_sets(sine_decs, inter=True)

save_path_sine = os.path.join(BASE_DIR, 'sine_func_dataset_int.pt')
torch.save({'training_x': training_sine[0],
            'training_y': training_sine[1],
            'test1_x': test_sets[0][0],
            'test1_y': test_sets[0][1],
            'test2_x': test_sets[1][0],
            'test2_y': test_sets[1][1],
            }, save_path_sine)

In [93]:
test_sets[1][0], test_sets[1][1][:5]

(tensor([[20.0000,  0.6826,  0.5002],
         [20.0000,  1.1486, -0.9961],
         [20.0000, -0.1078,  0.4233],
         ...,
         [20.0000, -0.7832,  0.2748],
         [20.0000,  1.3888,  1.2583],
         [20.0000, -0.3317, -0.1799]]),
 tensor([[1],
         [0],
         [1],
         [1],
         [1]], dtype=torch.int32))

We can also try a more RND-like approach. The goal of this is to make it so that the function that our methods have to learn is much more complicated than the ones above. 

In [94]:
import torch.nn as nn

def nn_func(training_examples: torch.Tensor):
    net = nn.Sequential(
        nn.Linear(2, 512), 
        nn.ReLU(),
        nn.Linear(512, 512), 
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(), 
        nn.Linear(512, 1), 
        nn.ReLU(),
        nn.Sigmoid(),
    )
    return (net(training_examples[:, 0:2]) > 0.5).squeeze()

training_nn = gen_data(nn_func)
test_sets = gen_test_sets(nn_func, inter=True)

save_path_sine = os.path.join(BASE_DIR, 'nn_func_dataset_int.pt')
torch.save({'training_x': training_nn[0],
            'training_y': training_nn[1],
            'test1_x': test_sets[0][0],
            'test1_y': test_sets[0][1],
            'test2_x': test_sets[1][0],
            'test2_y': test_sets[1][1],
            }, save_path_sine)


In [95]:
import zuko
import torch

from zuko.lazy import LazyInverse, Flow, NormalizingFlow
from zuko.flows import MaskedAutoregressiveTransform
from zuko.transforms import MonotonicRQSTransform, PermutationTransform

base_flow = zuko.flows.NSF(16)
flow = zuko.flows.Flow(base_flow.transform.inv, base_flow.base)

In [96]:
transform = flow().transform
z_original = torch.randn(1, 16)
mask = transform(z_original)
z_reconstructed = transform.inv(mask)

In [97]:
dist = flow()
mask = dist.rsample()

dist.log_prob(mask)

tensor(-18.0422, grad_fn=<AddBackward0>)

In [98]:
import torch
import zuko
import math

# Set seed for reproducibility
torch.manual_seed(42)

# 1. Setup the Batched Dimensions
batch_size = 16
event_features = 4  # D dimension

# 2. Define standard flow and invert it (Noise -> Mask)
base_flow = zuko.flows.MAF(features=event_features, transforms=2, hidden_features=[32, 32])
hypernet_flow = zuko.flows.Flow(base_flow.transform.inv, base_flow.base)

# Instantiate the active transform layer
transform = hypernet_flow().transform

# 3. Create a dummy Mask (x) vector WITH A BATCH DIMENSION
# Shape: [B, D] -> [16, 4]
x_input = torch.randn(batch_size, event_features, requires_grad=True)


# --- METHOD 1: BATCHED ZUKO INTERNAL LOG_PROB / LADJ ---
# Zuko processes batch spaces inherently.
z_zuko, ladj_zuko = transform.call_and_ladj(x_input)
# z_zuko shape: [16, 4] | ladj_zuko shape: [16]



# --- METHOD 2: BATCHED MANUAL JACOBIAN MATH ---
def forward_pass_func(x):
    return transform(x)

# Note: jacobian() outputs shape [B, D, B, D] -> [16, 4, 16, 4]
# It computes cross-derivatives between completely different batch samples.
full_cross_jacobian = torch.autograd.functional.jacobian(forward_pass_func, x_input)

# Extract only the independent batch-wise diagonal matrices [D, D] for each batch item
# We want the derivative of item i's output with respect to item i's input.
ladj_manual_list = []

for b in range(batch_size):
    # Slice out the specific [D, D] sub-matrix for batch element b
    local_jacobian = full_cross_jacobian[b, :, b, :] # Shape: [4, 4]
    
    # Calculate the Log of the Absolute Determinant for this batch row
    det_b = torch.linalg.det(local_jacobian)
    ladj_b = torch.log(torch.abs(det_b))
    ladj_manual_list.append(ladj_b)

# Stack back into a single batch tensor of shape [16]
ladj_manual = torch.stack(ladj_manual_list)


# --- BATCHED VERIFICATION PRINT-OUTS ---
print("--- BATCHED TEST RESULTS ---")
print(f"Zuko's Internal Tracking LADJ (First 3 Batch Items): {ladj_zuko[:3].detach().numpy()}")
print(f"Manually Computed Matrix LADJ (First 3 Batch Items): {ladj_manual[:3].detach().numpy()}")

# Calculate discrepancy over the entire batch
absolute_errors = torch.abs(ladj_zuko - ladj_manual)
max_batch_error = torch.max(absolute_errors).item()
print(f"Max Absolute Numerical Error across Batch:         {max_batch_error:.6e}")

# Check if it meets standard floating point tolerances
if max_batch_error < 1e-5:
    print("\n✅ SUCCESS: Zuko's inverted flow computes the exact correct batched LADJ math!")
else:
    print("\n❌ FAILURE: There is a batch discrepancy between internal tracking and manual matrix math.")

--- BATCHED TEST RESULTS ---
Zuko's Internal Tracking LADJ (First 3 Batch Items): [-0.6624558  -0.34273183 -0.6422415 ]
Manually Computed Matrix LADJ (First 3 Batch Items): [-0.662456   -0.34273162 -0.6422417 ]
Max Absolute Numerical Error across Batch:         3.576279e-07

✅ SUCCESS: Zuko's inverted flow computes the exact correct batched LADJ math!


In [ ]:
import dill
import numpy as np

with open('../results/mlp_run_simple.pl', 'rb') as file:
    results = dill.load(file)
    file.close()

ids = [seed['test_id']['acc'] for seed in results.values()]
np.mean(ids), np.std(ids)

(np.float64(0.8995683538913728), np.float64(0.13288848084998198))